[package]
name = "awesome-labels"
version = "0.1.0"
authors = ["Daijiro Chiba <chiba_daijiro@cyberagent.co.jp>"]
edition = "2018"

[dependencies]
github-rs = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.12.29"
regex = "1"